version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cats&dogs
      POSTGRES_USER: root
    ports:    
      - "5433:5432"
    volumes:
      - ./Database/sql/start:/docker-entrypoint-initdb.d
      - db-catsdogs-upload-service:/var/lib/postgresql/data

  cats:
    build: ./Cats
    ports: 
      - "5050:5000"
    environment:
      API_VERSION: v0
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cats&dogs
      POSTGRES_USER: root
      POSTGRES_HOST: postgres
    depends_on:
      - postgres

  dogs:
    build: ./Dogs
    ports: 
      - "5051:5000"
    environment:
      API_VERSION: v0
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cats&dogs
      POSTGRES_USER: root
      POSTGRES_HOST: postgres
    depends_on:
      - postgres

volumes:
  db-catsdogs-upload-service: